In [ ]:
!pip install torchtext==0.15.1
!pip install torch==2.1.0
!pip install transformers==4.27.1
!pip install datasets==2.17.0

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.0/2.0 MB 55.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 619.9/619.9 MB 2.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.6/4.6 MB 108.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 317.1/317.1 MB 4.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 11.8/11.8 MB 114.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 21.0/21.0 MB 89.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 849.3/849.3 kB 56.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 557.1/557.1 MB 3.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 168.4/168.4 MB 6.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 54.6/54.6 MB 13.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 102.6/102.6 MB 8.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 173.2/173.2 MB 6.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 17

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 670.2/670.2 MB 1.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 410.6/410.6 MB 4.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 14.1/14.1 MB 108.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 23.7/23.7 MB 84.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 823.6/823.6 kB 51.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 731.7/731.7 MB 2.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 121.6/121.6 MB 7.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 56.5/56.5 MB 11.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 124.2/124.2 MB 7.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 196.0/196.0 MB 6.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 209.8/209.8 MB 6.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 99.1/99.1 kB 9.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 106.7/106.7 kB 5.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.7/6.7 MB 28.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.8/7.8 MB 111.5 MB/s eta 0:00:00
  Attempting uninstall: tokenizers
    Found existing installation: tokenizers 0.21.0
    Uninstalling tokenizers-0.21.0:
      Successfully uninstalled tokenizers-0.21.0
  Attempting uninstall: transformers
    Found existing installation: transformers 4.48.2
    Uninstalling transformers-4.48.2:
      Successfully uninstalled transformers-4.48.2
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
sentence-transformers 3.4.1 requires transformers<5.0.0,>=4.41.0, but you have transformers 4.27.1 which is incompatible.


In [ ]:
import torch
import torch.nn as nn
from torchtext.data.utils import get_tokenizer
from torchtext.vocab import build_vocab_from_iterator
from torch.nn.utils.rnn import pad_sequence
from torch.utils.data import Dataset, DataLoader

qa_dataset = [
    {
        'context': 'My name is AIVN and I am from Vietnam.',
        'question': 'What is my name?',
        'answer': 'AIVN'
    },
    {
        'context': 'I love painting and my favorite artist is Vincent Van Gogh.',
        'question': 'What is my favorite activity?',
        'answer': 'painting'
    },
    {
        'context': 'I am studying computer science at the University of Tokyo.',
        'question': 'What am I studying?',
        'answer': 'computer science'
    }
]

data_size = len(qa_dataset)
data_size

3

In [ ]:
# Define tokenizer function
tokenizer = get_tokenizer('basic_english')

# Create a function to yield list of tokens
def yield_tokens(data):
    for item in data:
        yield tokenizer(item['context'] + ' ' + item['question'])

# Create vocabulary
vocab = build_vocab_from_iterator(
    yield_tokens(qa_dataset),
    specials=['<unk>', '<pad>', '<bos>', '<eos>', '<sep>']
)
vocab.set_default_index(vocab['<unk>'])
vocab.get_stoi()

{'vincent': 32,
 'vietnam': 31,
 'van': 30,
 'university': 29,
 'what': 11,
 '<sep>': 4,
 '<bos>': 2,
 'of': 24,
 'am': 10,
 'my': 7,
 'is': 6,
 'at': 19,
 '.': 8,
 'gogh': 22,
 '<eos>': 3,
 '<pad>': 1,
 'computer': 20,
 'painting': 25,
 'and': 12,
 '<unk>': 0,
 'artist': 18,
 'favorite': 13,
 'studying': 15,
 'i': 5,
 'aivn': 17,
 'tokyo': 28,
 'name': 14,
 'activity': 16,
 'from': 21,
 'love': 23,
 '?': 9,
 'science': 26,
 'the': 27}

In [ ]:
classes = set([item['answer'] for item in qa_dataset])
classes_to_idx = {
    cls_name: idx for idx, cls_name in enumerate(classes)
}
idx_to_classes = {
    idx: cls_name for idx, cls_name in enumerate(classes)
}
print(idx_to_classes)

{0: 'computer science', 1: 'painting', 2: 'AIVN'}


In [ ]:
MAX_QUESTION_LEN = 10
MAX_CONTEXT_LEN = 15
PAD_IDX = vocab['<pad>']

def pad_and_truncate(input_ids, max_seq_len):
    if len(input_ids) > max_seq_len:
        input_ids = input_ids[:max_seq_len]
    elif len(input_ids) < max_seq_len:
        input_ids += [PAD_IDX] * (max_seq_len - len(input_ids))

    return input_ids

def vectorize(question, context):
    input_question_ids = [vocab[token] for token in tokenizer(question)]
    input_context_ids = [vocab[token] for token in tokenizer(context)]

    input_question_ids = pad_and_truncate(input_question_ids, MAX_QUESTION_LEN)
    input_context_ids = pad_and_truncate(input_context_ids, MAX_CONTEXT_LEN)

    input_question_ids = torch.tensor(input_question_ids, dtype=torch.long)
    input_context_ids = torch.tensor(input_context_ids, dtype=torch.long)

    return input_question_ids, input_context_ids

In [ ]:
input_question_ids, input_context_ids = vectorize(
    qa_dataset[0]['context'],
    qa_dataset[0]['question']
)
print(input_question_ids)
print(input_context_ids)
print(classes_to_idx[qa_dataset[0]['answer']])

tensor([ 7, 14,  6, 17, 12,  5, 10, 21, 31,  8])
tensor([11,  6,  7, 14,  9,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1])
2


In [ ]:
class QADataset(Dataset):
    def __init__(self, data):
        self.data = data

    def __len__(self):
        return len(self.data)

    def __getitem__(self, idx):
        item = self.data[idx]
        question_text = item['question']
        context_text = item['context']

        input_question_ids, input_context_ids = vectorize(
            question_text, context_text
        )

        answer_text = item['answer']
        answer_id = classes_to_idx[answer_text]
        answer_id = torch.tensor(answer_id, dtype=torch.long)

        return input_question_ids, input_context_ids, answer_id

In [ ]:
def decode(input_ids):
    return ' '.join([vocab.lookup_token(token) for token in input_ids])

In [ ]:
train_dataset = QADataset(qa_dataset)
train_loader = DataLoader(train_dataset, batch_size=2, shuffle=True)

In [ ]:
for batch in train_loader:
    input_question_ids, input_context_ids, answer_id = batch
    print(input_question_ids, input_context_ids, answer_id)

tensor([[11, 10,  5, 15,  9,  1,  1,  1,  1,  1],
        [11,  6,  7, 13, 16,  9,  1,  1,  1,  1]]) tensor([[ 5, 10, 15, 20, 26, 19, 27, 29, 24, 28,  8,  1,  1,  1,  1],
        [ 5, 23, 25, 12,  7, 13, 18,  6, 32, 30, 22,  8,  1,  1,  1]]) tensor([0, 1])
tensor([[11,  6,  7, 14,  9,  1,  1,  1,  1,  1]]) tensor([[ 7, 14,  6, 17, 12,  5, 10, 21, 31,  8,  1,  1,  1,  1,  1]]) tensor([2])


In [ ]:
import torch.nn as nn
import torch.optim as optim

class QAModel(nn.Module):
    def __init__(self,
        vocab_size, embedding_dim, hidden_size,
        n_layers, n_classes
    ):
        super(QAModel, self).__init__()
        self.question_embedding = nn.Embedding(
            vocab_size, embedding_dim
        )
        self.context_embedding = nn.Embedding(
            vocab_size, embedding_dim
        )

        self.lstm = nn.LSTM(
            embedding_dim * 2, hidden_size,
            num_layers=n_layers,
            batch_first=True,
            bidirectional=True
        )
        self.fc = nn.Linear(hidden_size * 2, n_classes)

    def forward(self, question, context):
        question_embed = self.question_embedding(question)
        context_embed = self.context_embedding(context)

        combined = torch.cat(
            (question_embed, context_embed),
            dim=1
        )

        lstm_out, _ = self.lstm(combined)
        lstm_out = lstm_out[:, -1, :]

        out = self.fc(lstm_out)

        return out

# Model parameters
EMBEDDING_DIM = 64
HIDDEN_SIZE = 128
VOCAB_SIZE = len(vocab)
N_LAYERS = 2
N_CLASSES = len(classes)

model = QAModel(VOCAB_SIZE, EMBEDDING_DIM, HIDDEN_SIZE, N_LAYERS, N_CLASSES)

input_context = torch.randint(0, 10, size=(1, MAX_CONTEXT_LEN))
input_question = torch.randint(0, 10, size=(1, MAX_QUESTION_LEN))
model.eval()
with torch.no_grad():
    logits = model(input_question, input_context)

print(logits.shape)

torch.Size([1, 3])


In [ ]:
LR = 1e-3
optimizer = torch.optim.Adam(
    model.parameters(), lr=LR
)
criterion = nn.CrossEntropyLoss()

In [ ]:
EPOCHS = 20

model.train()
for _ in range(EPOCHS):
    for idx, (input_question_ids, input_context_ids, answer_id) in enumerate(train_loader):
        optimizer.zero_grad()
        outputs = model(input_question_ids, input_context_ids)
        loss = criterion(outputs, answer_id)
        loss.backward()
        optimizer.step()
        print(loss.item())

1.0841989517211914
1.2927165031433105
1.1452460289001465
1.0640251636505127
1.1059435606002808
1.052100419998169
1.0566418170928955
1.1575090885162354
1.1141493320465088
0.9826964139938354
1.1025049686431885
0.9516065716743469
0.994110643863678
1.120270013809204
1.0778357982635498
0.8329105377197266
1.0211389064788818
0.7478755712509155
0.9395896196365356
0.6099604964256287
0.5574547052383423
1.0696161985397339
0.7166918516159058
0.29412445425987244
0.5896788239479065
0.18702475726604462
0.4493691027164459
0.10719136893749237
0.3353314697742462
0.05937677249312401
0.05708907172083855
0.4555579721927643
0.036736197769641876
0.23250502347946167
0.02629716694355011
0.151454895734787
0.0562593936920166
0.02479725517332554
0.014737624675035477
0.03915075212717056


In [ ]:
model.eval()
with torch.no_grad():
    sample = qa_dataset[0]
    context, question, answer = sample.values()
    question_ids, context_ids = vectorize(question, context)
    question_ids = question_ids.unsqueeze(0)
    context_ids = context_ids.unsqueeze(0)
    outputs = model(question_ids, context_ids)
    _, predicted = torch.max(outputs.data, 1)
    print(f'Context: {context}')
    print(f'Question: {question}')
    print(f'Prediction: {idx_to_classes[predicted.numpy()[0]]}')

Context: My name is AIVN and I am from Vietnam.
Question: What is my name?
Prediction: AIVN


In [ ]:
print(classes_to_idx)

{'computer science': 0, 'painting': 1, 'AIVN': 2}
